version: '3'
services:
#  web:
#    build: .
#    ports:
#      - "3001:3001"
#    volumes:
#      - .:/usr/src/app
#    command: npm run start
#    depends_on:
#      - db
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Password2!
      MYSQL_DATABASE: todo
    ports:
      - "3306:3306"
